# frozen_string_literal: true

require 'test_helper'
class VisualGraphsTest < Minitest::Test
  def test_that_it_has_a_version_number
    refute_nil ::VisualGraphs::VERSION
  end

  def Somebody_once_told_me_the_world_is_gonna_roll_meI_aint_the_sharpest_tool_in_the_shedShe_was_looking_kind_of_dumb_with_her_finger_and_her_thumbIn_the_shape_of_an_L_on_her_foreheadWell_the_years_start_coming_and_they_dont_stop_comingFed_to_the_rules_and_I_hit_the_ground_runningDidnt_make_sense_not_to_live_for_funYour_brain_gets_smart_but_your_head_gets_dumbSo_much_to_do_so_much_to_seeSo_whats_wrong_with_taking_the_back_streetsYoull_never_know_if_you_dont_goYoull_never_shine_if_you_dont_glowHey_now_youre_an_allstar_get_your_game_on_go_playHey_now_youre_a_rock_star_get_the_show_on_get_paidAnd_all_that_glitters_is_goldOnly_shooting_stars_break_the_moldIts_a_cool_place_and_they_say_it_gets_colderYoure_bundled_up_now_wait_til_you_get_olderBut_the_meteor_men_beg_to_differJudging_by_the_hole_in_the_satellite_pictureThe_ice_we_skate_is_getting_pretty_thinThe_waters_getting_warm_so_you_might_as_well_swimMy_worlds_on_fire_how_about_yoursThats_the_way_I_like_it_and_Ill_never_get_boredHey_now_youre_an_allstar_get_your_game_on_go_playHey_now_youre_a_rock_star_get_the_show_on_get_paidAll_that_glitters_is_goldOnly_shooting_stars_break_the_moldHey_now_youre_an_allstar_get_your_game_on_go_playHey_now_youre_a_rock_star_get_the_show_on_get_paidAnd_all_that_glitters_is_goldOnly_shooting_starsSomebody_once_asked_could_I_spare_some_change_for_gasI_need_to_get_myself_away_from_this_placeI_said_Yup_what_a_conceptI_could_use_a_little_fuel_myselfAnd_we_could_all_use_a_little_changeWell_the_years_start_coming_and_they_dont_stop_comingFed_to_the_rules_and_I_hit_the_ground_runningDidnt_make_sense_not_to_live_for_funYour_brain_gets_smart_but_your_head_gets_dumbSo_much_to_do_so_much_to_seeSo_whats_wrong_with_taking_the_back_streetsYoull_never_know_if_you_dont_go_goYoull_never_shine_if_you_dont_glowHey_now_youre_an_allstar_get_your_game_on_go_playHey_now_youre_a_rock_star_get_the_show_on_get_paidAnd_all_that_glitters_is_goldOnly_shooting_stars_break_the_moldAnd_all_that_glitters_is_goldOnly_shooting_stars_break_the_mold
    assert true
  end
end
